export enum RegulatoryEventType {
  CONTROLE_REGLEMENTAIRE = 'CONTROLE_REGLEMENTAIRE',
  AUDIT_CERTIFICATION    = 'AUDIT_CERTIFICATION',
  FORMATION             = 'FORMATION',
  CSST                  = 'CSST',
  ANALYSES_EAU          = 'ANALYSES_EAU',
  AUDIT_ENERGIE         = 'AUDIT_ENERGIE',
  MEDECINE_TRAVAIL      = 'MEDECINE_TRAVAIL',
  REVUE_DIRECTION       = 'REVUE_DIRECTION',
  CONTROLE_INCENDIE     = 'CONTROLE_INCENDIE',
  EXERCICE_EVACUATION   = 'EXERCICE_EVACUATION',
  MESURES_EMISSIONS     = 'MESURES_EMISSIONS',
}